apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues-api
spec:
  selector:
    matchLabels:
      app: issues-api
  template:
    metadata:
      labels:
        app: issues-api
    spec:
      containers:
      - name: issues-api
        image: jeffrygonzalez/issues-api-aug-2023:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ConnectionStrings__data
            value: Server=172.22.0.0/16;Database=issues_data;User Id=user;Password=password
          - name: business-clock-api
            value: http://business-clock-service
        ports:
        - containerPort: 80
