apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-clock
spec:
  selector:
    matchLabels:
      app: business-clock
  template:
    metadata:
      labels:
        app: business-clock
    spec:
      containers:
      - name: business-clock
        image: jeffrygonzalez/clock-api-bsd-aug-2023:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
